### ISSUE TITLE
Embed in CSS instead of using SVG

### ISSUE THREAD

**Issue by 3e9b** [FlorianWoelki/obsidian-iconize#234]
**Is your feature request related to a problem? Please describe.**
Even with the new update, the syncing is still acting up.

**Describe the solution you'd like**
Instead of trying to sync the SVG files, embed the css code inline for each folder. Here's a good example of this working:

```css
.nav-folder:not(.mod-root) .nav-folder-title-content::before {
  display: inline-block;
  content: "";
  margin-right: 5px;
  vertical-align: text-bottom;
  height: 20px;
  width: 20px;
  background-color: currentColor;
}

.nav-folder:not(.mod-root):not(.is-collapsed) .nav-folder-title-content::before {
  -webkit-mask: url("data:image/svg+xml;charset=UTF-8,%3csvg viewBox='0 0 512 512' version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'%3e%3ctitle%3efolder-open-outline%3c/title%3e%3cg id='Page-1' stroke='none' stroke-width='1' fill='none' fill-rule='evenodd'%3e%3cg id='folder-open' fill='%23000000' transform='translate(42.666667, 85.333333)'%3e%3cpath d='M384,128 L384,42.6666667 L232.0416,42.6666667 L178.0832,1.42108547e-14 L7.10542736e-15,1.42108547e-14 L7.10542736e-15,341.333333 L60.9376,341.333333 L352.437547,341.333333 L361.604267,341.333333 L426.354347,128 L384,128 Z M42.6666667,253.44 L42.6666667,42.6666667 L163.24992,42.6666667 L217.20832,85.3333333 L341.333333,85.3333333 L341.333333,128 L82.0209067,128 L42.6666667,253.44 Z M329.979093,298.666667 L73.1874133,298.666667 L113.354027,170.666667 L368.812373,170.666667 L329.979093,298.666667 Z' id='Shape'%3e%3c/path%3e%3c/g%3e%3c/g%3e%3c/svg%3e") no-repeat;
}
```
