### ISSUE TITLE
Add the lucide class names to Lucide icons, like "lucide-link" for link. (the Obsidian UI does this with all of their icons)

### ISSUE THREAD

**Issue by YousufSSyed** [FlorianWoelki/obsidian-iconize#292]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
Not a problem, but I have my own theme that replaces all the lucide icons that would be visible in vault with SF Symbols. I use CSS rules like this one, while it only takes a few more for the folder icons I want to add, I'd like the plugin to add the class names so that the ones I already have can apply automatically. 

```css
.lucide-link {
display: none;
}

:has(> .lucide-link):after {
content: ...
}
```
