### ISSUE TITLE
The iconize element is incorrectly added to a note without icon

### ISSUE THREAD

**Issue by Moyf** [FlorianWoelki/obsidian-iconize#627]
**Describe the bug**
As shown in the image, the `iconize-inline-title-wrapper` element is incorrectly added to note pages that do not have an icon.
![image](https://github.com/user-attachments/assets/8657a6a3-fefb-4c70-81a4-f72bfdc3676f)

This 📏 icon is actually from the other note, and it incorrectly appeared in my Daily Note.

The reason it is invisible but I care is that I want to use CSS to make the Iconize plugin work with the **Pixel Banner** plugin by adjusting the `margin-top` property to position the icon at the boundary of the banner. (Just like Notion's style)
![image](https://github.com/user-attachments/assets/8abd6ecc-02c1-42a8-bc8d-70badebf8d9a)

However, this invisible iconize element makes the judgment more complicated.. 🤔

**To Reproduce**
1. Click on some notes with icon
2. Switch to another note without icon
3. Open the DevTool and look into `cm-sizer` structure
4. See the icon elem from previous note

**Expected behavior**
Remove the elem or add a `.no-icon` class into the elem's class?

**Additional context**
I noticed that this element has a `display: none` attribute:
![image](https://github.com/user-attachments/assets/42e02c7f-c54b-465d-9a77-6b708d56297e)

So currently I use this css to achieve what I want:
```css
.cm-sizer:has(.iconize-inline-title-wrapper):has(.pixel-banner-image):has(.iconize-title-icon:not([style*='display: none;'])) .iconize-inline-title-wrapper {
  margin-top: calc(-1 * var(--emoji-icon-size)) !important;
}
```
